[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
# startCommand handled by Dockerfile CMD now

[[services]]
name = "web"

[services.volumes]
uploads = "/app/uploads"