[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "echo 'Starting migration...' && npx prisma migrate deploy && echo 'Migration completed, starting server...' && node server.js"

[[services]]
name = "web"

[services.volumes]
uploads = "/app/uploads"