[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "npx prisma migrate deploy && node server.js"

[[services]]
name = "web"

[services.volumes]
uploads = "/app/uploads"